# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\"\x89\x02\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x1a\n\x05genre\x18\x05 \x01(\x0e\x32\x0b.Book.Genre\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\"\n\tpublisher\x18\x07 \x01(\x0b\x32\x0f.Book.Publisher\x1a*\n\tPublisher\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"L\n\x05Genre\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46ICTION\x10\x01\x12\x0f\n\x0bNON_FICTION\x10\x02\x12\x0b\n\x07SCIENCE\x10\x03\x12\x0b\n\x07HISTORY\x10\x04\"&\n\x0e\x42ookCollection\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book\"\x1b\n\x0b\x42ookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"#\n\x0c\x42ookResponse\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book25\n\x0b\x42ookService\x12&\n\x07GetBook\x12\x0c.BookRequest\x1a\r.BookResponseB\x10\n\x0corg.ds.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014org.ds.protoP\001'
  _globals['_BOOK']._serialized_start=15
  _globals['_BOOK']._serialized_end=280
  _globals['_BOOK_PUBLISHER']._serialized_start=160
  _globals['_BOOK_PUBLISHER']._serialized_end=202
  _globals['_BOOK_GENRE']._serialized_start=204
  _globals['_BOOK_GENRE']._serialized_end=280
  _globals['_BOOKCOLLECTION']._serialized_start=282
  _globals['_BOOKCOLLECTION']._serialized_end=320
  _globals['_BOOKREQUEST']._serialized_start=322
  _globals['_BOOKREQUEST']._serialized_end=349
  _globals['_BOOKRESPONSE']._serialized_start=351
  _globals['_BOOKRESPONSE']._serialized_end=386
  _globals['_BOOKSERVICE']._serialized_start=388
  _globals['_BOOKSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
